name: Qodo AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Qodo AI Review
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Required as Qodo uses OpenAI under the hood
        with:
          config-file: .pr_agent.toml
          best-practices-file: best_practices.md

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "VITE_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env

      - name: Type Check
        run: npm run type-check || npm run tsc || echo "No type checking configured"
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Lint
        run: npm run lint || echo "No linting configured"
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Test
        run: npm run test || echo "No tests configured"
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build
        run: npm run build
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}